export const ARTIST_RELATED_REQUEST = 'ARTIST_RELATED_REQUEST';
export const ARTIST_RELATED_SUCCESS = 'ARTIST_RELATED_SUCCESS';
export const ARTIST_RELATED_FAIL = 'ARTIST_RELATED_FAIL';
export const ARTIST_RELATED_RESET = 'ARTIST_RELATED_RESET';

export const SIMILAR_ARTISTS_REQUEST = 'SIMILAR_ARTISTS_REQUEST';
export const SIMILAR_ARTISTS_SUCCESS = 'SIMILAR_ARTISTS_SUCCESS';
export const SIMILAR_ARTISTS_FAIL = 'SIMILAR_ARTISTS_FAIL';
export const SIMILAR_ARTISTS_RESET = 'SIMILAR_ARTISTS_RESET';

export const ARTIST_LIST_REQUEST = 'ARTIST_LIST_REQUEST';
export const ARTIST_LIST_SUCCESS = 'ARTIST_LIST_SUCCESS';
export const ARTIST_LIST_FAIL = 'ARTIST_LIST_FAIL';
export const ARTIST_LIST_RESET = 'ARTIST_LIST_RESET';

export const ARTIST_BY_ID_REQUEST = 'ARTIST_BY_ID_REQUEST';
export const ARTIST_BY_ID_SUCCESS = 'ARTIST_BY_ID_SUCCESS';
export const ARTIST_BY_ID_FAIL = 'ARTIST_BY_ID_FAIL';
export const ARTIST_BY_ID_RESET = 'ARTIST_BY_ID_RESET';

export const ARTIST_GALLERY_ADDRESS_UPDATE_REQUEST =
  ' ARTIST_GALLERY_ADDRESS_REQUEST';
export const ARTIST_GALLERY_ADDRESS_UPDATE_SUCCESS =
  ' ARTIST_GALLERY_ADDRESS_SUCCESS';
export const ARTIST_GALLERY_ADDRESS_UPDATE_FAIL =
  ' ARTIST_GALLERY_ADDRESS_FAIL';

export const ARTIST_IS_TALENT_REQUEST = 'ARTIST_IS_TALENT_REQUEST';
export const ARTIST_IS_TALENT_SUCCESS = 'ARTIST_IS_TALENT_SUCCESS';
export const ARTIST_IS_TALENT_FAIL = 'ARTIST_IS_TALENT_FAIL';
export const ARTIST_IS_TALENT_RESET = 'ARTIST_IS_TALENT_RESET';
